config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/jenkins-pipeline-library:
      branch: feature/get_badge
      repo: https://github.com/indigo-dc/jenkins-pipeline-library
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-burgundy-budgerigar.sh
        container: qc.acc_wheezy-flax-lemur
  QC.Doc:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-sapphire-coyote.sh
        container: qc.doc_greasy-celadon-bee
      github.com/indigo-dc/jenkins-pipeline-library git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-sapphire-dunker.sh
        container: qc.doc_shabby-zucchini-flamingo
      github.com/indigo-dc/jenkins-pipeline-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-wheat-ocelot.sh
        container: qc.doc_zippy-blue-ferret
      github.com/indigo-dc/jenkins-pipeline-library restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cornflower-fowl.sh
        container: qc.doc_hazy-rust-grouse
  QC.Lic:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-indigo-woodlouse.sh
        container: qc.lic_boozy-fuchsia-malamute
  QC.Met:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-salmon-burmese.sh
        container: qc.met_slimy-seashell-sloth
  QC.Sec:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-maroon-butterfly.sh
        container: qc.sec_shaky-chestnut-buffalo
  QC.Sty:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-khaki-buzzard.sh
        container: qc.sty_slimy-cornflower-magpie
  QC.Ver:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-mustard-lizard.sh
        container: qc.ver_sleepy-tangerine-oyster
timeout: 5400
