config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/jenkins-pipeline-library:
      repo: https://github.com/indigo-dc/jenkins-pipeline-library
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-brown-baboon.sh
        container: qc.acc_hasty-silver-setter
  QC.Doc:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library find_readme.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-corn-maltese.sh
        container: qc.doc_gimpy-cream-hedgehog
      github.com/indigo-dc/jenkins-pipeline-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-brown-newt.sh
        container: qc.doc_geeky-purple-hedgehog
      github.com/indigo-dc/jenkins-pipeline-library restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-razzmatazz-reindeer.sh
        container: qc.doc_snappy-pumpkin-lemur
  QC.Lic:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-rust-chameleon.sh
        container: qc.lic_squeaky-cerise-zebra
  QC.Met:
    repos:
      github.com/indigo-dc/jenkins-pipeline-library validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-black-collie.sh
        container: qc.met_lovely-russet-gar
timeout: 600
